llm:
  models:
    - name: gpt-4o
      value: gpt-4o
    - name: gpt-3.5-turbo
      value: gpt-3.5-turbo
    - name: gpt-4-turbo
      value: gpt-4-turbo
    - name: yi-34b-chat
      value: yi-34b-chat-0205

stt:
  models:
    - name: chatGPT-whisper
      value: whisper-1
    - name: azure-voice
      value: azure

tts:
  models:
    - name: chatGPT-tts
      value: tts-1
    - name: edge-tts
      value: edge
