llm:
  models:
    - name: gpt-4o
      value: gpt-4o
      server: https://api.openai.com/v1
    - name: gpt-3.5-turbo
      value: gpt-3.5-turbo
      server: https://api.openai.com/v1
    - name: gpt-4-turbo
      value: gpt-4-turbo
      server: https://api.openai.com/v1
    - name: yi-34b-chat
      value: yi-34b-chat-0205
      server: https://api.lingyiwanwu.com/v1

stt:
  models:
    - name: chatGPT-whisper
      value: whisper-1
      server: https://api.openai.com/v1
    - name: azure-voice
      value: azure
      server: ""

tts:
  models:
    - name: chatGPT-tts
      value: tts-1
      server: https://api.openai.com/v1
    - name: edge-tts
      value: edge
      server: ""
